# Generated by Django 5.1.1 on 2024-09-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher_remove_student_middle_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
