# Generated by Django 5.2.2 on 2025-06-05 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_verified_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be either 10 digits starting with '0' or 13 digits starting with '+255' followed by 9 digits.", regex='^(0\\d{9}|\\+255\\d{9})$')], verbose_name='phone number'),
        ),
    ]
